#!/usr/bin/env bash
# build_backend_benches.sh — compile the three direct-to-backend
# microbenches that bypass Janus.
#
# Outputs three binaries under scripts/build/:
#   bench_etcd_libetcd   (variant A: same etcd-cpp-apiv3 client Janus uses)
#   bench_etcd_grpc      (variant B: raw grpc++ + etcdserverpb)
#   bench_mongo_cxx      (variant C: same mongocxx Janus uses)
#
# Re-uses third_party/etcd-cpp-apiv3/build/ in-tree (no sudo install needed
# — the resulting binaries carry an rpath to that build dir so they find
# libetcd-cpp-api.so at runtime).
#
# Pre-reqs (install once if missing):
#   sudo apt-get install -y build-essential cmake pkg-config libssl-dev \
#       libboost-all-dev libprotobuf-dev protobuf-compiler \
#       libgrpc++-dev protobuf-compiler-grpc libcpprest-dev
#   # mongocxx is expected at /usr/local/lib/libmongocxx.so* (already present)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
THIRD="${ROOT}/third_party"
ETCD_LIB_SRC="${THIRD}/etcd-cpp-apiv3"
ETCD_LIB_BUILD="${ETCD_LIB_SRC}/build"
ETCD_LIB_SO_DIR="${ETCD_LIB_BUILD}/src"
ETCD_PROTO_GEN="${ETCD_LIB_BUILD}/proto/gen/proto"   # generated by etcd-cpp-apiv3 build
BUILD="${SCRIPT_DIR}/build"
mkdir -p "${BUILD}"

CXX="${CXX:-g++}"
CXXSTD="-std=c++17 -O2 -g -Wall -Wno-unused-parameter -pthread"

# Match whatever protobuf etcd-cpp-apiv3 was built against. cmake will
# auto-pick: prefers ~/.local if present (e.g. zoo box has 3.21.12), else
# falls back to system (e.g. AWS hosts use system 3.12.4 + grpc 1.30.2).
# We mirror that choice here so the .pb.cc files we link match the headers.
LOCAL_PB_PREFIX="${LOCAL_PB_PREFIX:-}"
if [ -z "${LOCAL_PB_PREFIX}" ] && [ -f "${HOME}/.local/lib/libprotobuf.so" ]; then
  LOCAL_PB_PREFIX="${HOME}/.local"
fi
PB_INC=""
PB_LIB=""
if [ -n "${LOCAL_PB_PREFIX}" ]; then
  PB_INC="-I${LOCAL_PB_PREFIX}/include"
  PB_LIB="-L${LOCAL_PB_PREFIX}/lib -Wl,-rpath,${LOCAL_PB_PREFIX}/lib"
  echo "[build] using protobuf at ${LOCAL_PB_PREFIX}"
else
  echo "[build] using system protobuf"
fi

# ---- 1. Build etcd-cpp-apiv3 in-tree (no sudo install) --------------------
if [ ! -f "${ETCD_LIB_SO_DIR}/libetcd-cpp-api.so" ]; then
  echo "[build] etcd-cpp-apiv3 not built; configuring + building in-tree"
  mkdir -p "${ETCD_LIB_BUILD}"
  (cd "${ETCD_LIB_BUILD}" && \
    cmake .. \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_ETCD_TESTS=OFF \
      -DBUILD_SHARED_LIBS=ON >/dev/null && \
    cmake --build . -- -j"$(nproc)")
fi

# Sanity check: generated proto headers we need for the grpc bench live in
# ${ETCD_PROTO_GEN}. The etcd-cpp-apiv3 build emits rpc.pb.h, rpc.grpc.pb.h,
# kv.pb.h, auth.pb.h, etc.
if [ ! -f "${ETCD_PROTO_GEN}/rpc.grpc.pb.h" ]; then
  echo "ERROR: ${ETCD_PROTO_GEN}/rpc.grpc.pb.h missing — etcd-cpp-apiv3 build incomplete?" >&2
  exit 1
fi

# ---- 2. Compile bench_etcd_libetcd ----------------------------------------
echo "[build] bench_etcd_libetcd"
"${CXX}" ${CXXSTD} \
    -I"${ETCD_LIB_SRC}" ${PB_INC} -I/usr/local/include \
    "${SCRIPT_DIR}/bench_etcd_libetcd.cc" \
    -L"${ETCD_LIB_SO_DIR}" -Wl,-rpath,"${ETCD_LIB_SO_DIR}" \
    ${PB_LIB} \
    -o "${BUILD}/bench_etcd_libetcd" \
    -letcd-cpp-api -lcpprest -lgrpc++ -lprotobuf -lssl -lcrypto -lpthread

# ---- 3. Compile bench_etcd_grpc -------------------------------------------
echo "[build] bench_etcd_grpc"
# Cherry-pick only the .pb.cc files KV.Put actually transitively needs:
#   rpc.{pb,grpc.pb}.cc → kv.pb.cc, auth.pb.cc, gogoproto/gogo.pb.cc,
#                         google/api/annotations.pb.cc, google/api/http.pb.cc
# We do NOT include etcdserver.pb.cc / v3election / v3lock — those use newer
# protobuf APIs and aren't reachable from KV.Put.
GEN_SRC=(
  "${ETCD_PROTO_GEN}/rpc.pb.cc"
  "${ETCD_PROTO_GEN}/rpc.grpc.pb.cc"
  "${ETCD_PROTO_GEN}/kv.pb.cc"
  "${ETCD_PROTO_GEN}/auth.pb.cc"
  "${ETCD_PROTO_GEN}/gogoproto/gogo.pb.cc"
  "${ETCD_PROTO_GEN}/google/api/annotations.pb.cc"
  "${ETCD_PROTO_GEN}/google/api/http.pb.cc"
)

"${CXX}" ${CXXSTD} \
    -I"${ETCD_PROTO_GEN}" ${PB_INC} -I/usr/local/include \
    "${SCRIPT_DIR}/bench_etcd_grpc.cc" "${GEN_SRC[@]}" \
    ${PB_LIB} \
    -o "${BUILD}/bench_etcd_grpc" \
    -lgrpc++ -lgrpc -lprotobuf -lpthread

# ---- 4. Compile bench_mongo_cxx -------------------------------------------
echo "[build] bench_mongo_cxx"
MONGO_CFLAGS=$(pkg-config --cflags libmongocxx)
MONGO_LIBS=$(pkg-config --libs libmongocxx)
"${CXX}" ${CXXSTD} \
    ${MONGO_CFLAGS} \
    "${SCRIPT_DIR}/bench_mongo_cxx.cc" \
    -o "${BUILD}/bench_mongo_cxx" \
    ${MONGO_LIBS} -lpthread

echo
echo "[build] OK — binaries in ${BUILD}/"
ls -1 "${BUILD}"/bench_*
