#!/bin/bash
# gen_akkio_client_config.sh — emit the Akkio-style per-host client layout
# for the latency experiment (see scripts/run_akkio_etcd.sh).
#
# Total client sites = sum(per-host counts). Default split (passed via env)
# puts 46/42/10/2/0 sites on zoo1..zoo5 respectively.
#
# Each client site runs with whatever concurrent_*.yml the caller picks
# (typically concurrent_20.yml for Akkio, which yields 20 outstanding
# in-flight requests per site under open loop).
#
# Output: config/akkio_<Z1>_<Z2>_<Z3>_<Z4>_<Z5>c1s5r1p-zoo.yml. Idempotent.
#
# Usage:
#   ./gen_akkio_client_config.sh [Z1 Z2 Z3 Z4 Z5]
#     (defaults: 46 42 10 2 0)

set -euo pipefail

Z1="${1:-46}"
Z2="${2:-42}"
Z3="${3:-10}"
Z4="${4:-2}"
Z5="${5:-0}"
TOTAL=$((Z1 + Z2 + Z3 + Z4 + Z5))

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_DIR/config/akkio_${Z1}_${Z2}_${Z3}_${Z4}_${Z5}c1s5r1p-zoo.yml"

# Width to match c001..cNNN when TOTAL >= 100.
if [ "$TOTAL" -lt 100 ]; then WIDTH=2; else WIDTH=3; fi

declare -a cids
declare -a cids_zoo
idx=0
for zi in 1 2 3 4 5; do
  var="Z$zi"
  count="${!var}"
  for i in $(seq 1 "$count"); do
    idx=$((idx + 1))
    cid="c$(printf "%0${WIDTH}d" "$idx")"
    cids+=("$cid")
    cids_zoo+=("zoo$zi")
  done
done

{
  echo "# Akkio client layout: $Z1/$Z2/$Z3/$Z4/$Z5 sites on zoo1..zoo5 (total $TOTAL)."
  echo "# Generated by scripts/gen_akkio_client_config.sh."
  echo ""
  echo "site:"
  echo "  server: # each line is a partition, the first is the master site_name:port"
  echo "    - [\"s101:38000\", \"s201:38001\", \"s301:38002\", \"s401:38003\", \"s501:38004\"]"
  echo "  client: # each line is a partition"
  printf "    - ["
  for i in "${!cids[@]}"; do
    if [ $((i % 5)) -eq 0 ] && [ "$i" -gt 0 ]; then printf "\n       "; fi
    printf "\"%s\"" "${cids[$i]}"
    if [ "$i" -lt $((${#cids[@]} - 1)) ]; then printf ", "; fi
  done
  echo "]"
  echo ""
  echo "process:"
  echo "  s101: zoo1"
  echo "  s201: zoo2"
  echo "  s301: zoo3"
  echo "  s401: zoo4"
  echo "  s501: zoo5"
  for i in "${!cids[@]}"; do
    echo "  ${cids[$i]}: ${cids_zoo[$i]}"
  done
  echo ""
  echo "host:"
  echo "  zoo1: 130.245.173.101"
  echo "  zoo2: 130.245.173.102"
  echo "  zoo3: 130.245.173.103"
  echo "  zoo4: 130.245.173.104"
  echo "  zoo5: 130.245.173.105"
} > "$OUT"

echo "$OUT"
