#!/bin/bash
# run_adaptive_sweep.sh — adaptive client-count sweep to find the peak
# throughput under a tail-latency SLO for a single protocol.
#
# Protocol flow:
#   1. Measure p50 at N=1 as a sanity baseline (for CPU idle check).
#   2. SLO: zoo2 p90 <= 1000 ms. A point "trips stop" when zoo2 p90 > 1000 ms.
#   3. Probe N=50 and N=100. If either trips stop, bisect between the last
#      in-SLO point and the first out-of-SLO point until |hi-lo| <= TOL.
#      Otherwise extend upward (150, 200, 300, 500) until a stop fires.
#   4. After bisect, densely probe N values in [lo-2, hi+2] that were not
#      already measured, so the throughput peak can be pinned down past the
#      coarse bisect boundary.
#   5. Peak = argmax(tput) over all measured rows where zoo2_p90 <= 1000 ms.
#   6. Produces <result_dir>/<label>-adaptive.csv and a pretty-printed
#      per-protocol table (tput + zoo2/zoo3 p50/p90/p99 + per-host CPU avg).
#
# Usage:
#   SERVER_CORE_ID=17 ./run_adaptive_sweep.sh <label> <cfg.yml> <mode> <result_dir>
# Example:
#   SERVER_CORE_ID=17 ./run_adaptive_sweep.sh naive_raft none_naive_raft.yml 0 results/2026-04-20-naive-raft

set -uo pipefail

LABEL="$1"
CFG="$2"
MODE="$3"
RDIR="$4"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
mkdir -p "$RDIR"

BISECT_TOL=1     # stop bisecting once |hi - lo| <= 1 client
UP_SEQ=(150 200 300 500)  # extension points if N=100 doesn't saturate
STOP_P90_MS=1000 # SLO: stop when zoo2 p90 exceeds this (in ms)
DENSE_PAD=2      # dense-probe window: [last_ok - PAD, first_stop + PAD]

export SERVER_CORE_ID="${SERVER_CORE_ID:-1}"

OUT_CSV="$RDIR/${LABEL}-adaptive.csv"
echo "N,tput,zoo2_p50,zoo2_p90,zoo2_p99,zoo3_p50,zoo3_p90,zoo3_p99,zoo1_cpu,zoo2_cpu,zoo3_cpu,zoo4_cpu,zoo5_cpu,avg_cpu,fp_att,fp_succ,fp_eff,fp_rate,fp_eff_rate,stopped" > "$OUT_CSV"

# Snapshot the exact experiment setting for this run so the results folder
# is self-contained (the canonical spec can drift in docs/ after the fact).
cat > "$RDIR/SETTING.md" <<EOF
# Experiment setting snapshot — ${LABEL}

Generated by \`scripts/run_adaptive_sweep.sh\` at $(date -Iseconds).

Canonical spec: [docs/max_throughput_experiment_setting.md](../../docs/max_throughput_experiment_setting.md).
Git commit at run time: $(cd "$REPO_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "unknown") $(cd "$REPO_DIR" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

## Invocation

- Label:           \`${LABEL}\`
- Protocol cfg:    \`config/${CFG}\`
- Mode flag (-m):  \`${MODE}\`
- Client concurrent: \`concurrent_500.yml\` (500 per client)
- Workload:        \`rw_1000000.yml\`, \`client_open.yml\`
- Duration:        30 s per data point
- WAN delay:       \`WAN_DELAY_MS=20\` (40 ms injected RTT)
- Server core pin: \`SERVER_CORE_ID=${SERVER_CORE_ID}\` (reactor + disk-poll + main server thread)
- Leader routing:  locale_id=1 (zoo2 / .102) for leader-routing protocols
- SLO:             zoo2 p90 <= ${STOP_P90_MS} ms
- Sweep:           N=1 (baseline on zoo2), 50, 100, then bisect/extend until zoo2 p90 > ${STOP_P90_MS} ms,
                   followed by a dense +/-${DENSE_PAD} probe around the knee
- Peak rule:       argmax(tput) over rows with zoo2 p90 <= ${STOP_P90_MS} ms

## CPU metric

Per-host: mean ("server average") of ~10 per-second core-${SERVER_CORE_ID}
\`/proc/stat\` samples over the mid-10 s window (experiment seconds 10–19).
Headline number is the avg across the 5 hosts' means.

## Files in this folder

- \`${LABEL}-adaptive.csv\`  — wide results CSV (one row per N attempted)
- \`${LABEL}-N<n>c500-zooK.res\`          — per-host raw stdout
- \`${LABEL}-N<n>c500-zooK-cpustat.txt\`  — per-host 1 s /proc/stat samples
- \`${LABEL}-N<n>c500.runlog\`            — orchestration log for that N
EOF

run_point() {
  local N="$1"
  if [ "$N" -eq 1 ]; then
    # Baseline: place the single client on zoo2 (the fixed leader for
    # leader-routing protocols). Otherwise "zoo2 p50" is empty and the
    # stop criterion (2x baseline) degenerates. Named -zoo2 so we don't
    # stomp the generic 1c1s5r5p-zoo.yml that callers of gen_client_config
    # would produce for other uses.
    local CLI_CFG="1c1s5r5p-zoo2.yml"
    local OUT="$REPO_DIR/config/$CLI_CFG"
    if [ ! -f "$OUT" ]; then
      cat > "$OUT" <<'EOF'

site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:38000", "s201:38001", "s301:38002", "s401:38003", "s501:38004"]
  client: # each line is a partition
    - ["c01"]


process:
  s101: zoo1
  s201: zoo2
  s301: zoo3
  s401: zoo4
  s501: zoo5
  c01: zoo2

host:
  zoo1: 130.245.173.101
  zoo2: 130.245.173.102
  zoo3: 130.245.173.103
  zoo4: 130.245.173.104
  zoo5: 130.245.173.105
EOF
    fi
  else
    bash "$SCRIPT_DIR/gen_client_config.sh" "$N"
    local CLI_CFG="${N}c1s5r5p-zoo.yml"
  fi
  local run_label="${LABEL}-N${N}c500"
  echo "  [$run_label] running..."
  bash "$SCRIPT_DIR/run_single_exp.sh" "$CFG" "$MODE" concurrent_500.yml "$run_label" "$RDIR" "$CLI_CFG" \
    > "$RDIR/${run_label}.runlog" 2>&1 || true

  local total=0
  local fp_att_total=0 fp_succ_total=0 fp_eff_total=0
  local -a CPUS P50S P90S P99S
  for zi in 0 1 2 3 4; do
    local f="$RDIR/${run_label}-zoo$((zi+1)).res"
    local tp
    tp=$(grep -m1 "Mid throughput" "$f" 2>/dev/null | awk '{print $NF}')
    local cpu
    cpu=$(grep -m1 "server average" "$f" 2>/dev/null | awk '{print $NF}')
    if [ -z "$cpu" ]; then
      cpu=$(grep -m1 "server median" "$f" 2>/dev/null | awk '{print $NF}')
    fi
    local stats_line
    stats_line=$(grep "All-efficient-attempts *statistics" "$f" 2>/dev/null | head -1)
    local p50 p90 p99
    p50=$(awk '{for(i=1;i<=NF;i++) if($i=="50pct"){print $(i+1);exit}}' <<< "$stats_line")
    p90=$(awk '{for(i=1;i<=NF;i++) if($i=="90pct"){print $(i+1);exit}}' <<< "$stats_line")
    p99=$(awk '{for(i=1;i<=NF;i++) if($i=="99pct"){print $(i+1);exit}}' <<< "$stats_line")
    [ -z "$tp" ]  && tp=0
    [ -z "$cpu" ] && cpu=0
    [ -z "$p50" ] && p50=0
    [ -z "$p90" ] && p90=0
    [ -z "$p99" ] && p99=0
    CPUS[$zi]=$cpu
    P50S[$zi]=$p50
    P90S[$zi]=$p90
    P99S[$zi]=$p99
    total=$(awk -v t="$total" -v x="$tp" 'BEGIN{print t+x}')

    # Parse "Fastpath statistics attempted N successed M rate(pct) R
    # efficient_successed E efficient_rate(pct) ER". Aggregate across
    # hosts by summing counts; rates derived from the totals so a
    # saturated host doesn't distort the average.
    local fp_line
    fp_line=$(grep -m1 "Fastpath statistics" "$f" 2>/dev/null)
    if [ -n "$fp_line" ]; then
      local fp_att fp_succ fp_eff
      fp_att=$(awk '{for(i=1;i<=NF;i++) if($i=="attempted"){print $(i+1);exit}}' <<< "$fp_line")
      fp_succ=$(awk '{for(i=1;i<=NF;i++) if($i=="successed"){print $(i+1);exit}}' <<< "$fp_line")
      fp_eff=$(awk '{for(i=1;i<=NF;i++) if($i=="efficient_successed"){print $(i+1);exit}}' <<< "$fp_line")
      [ -z "$fp_att" ]  && fp_att=0
      [ -z "$fp_succ" ] && fp_succ=0
      [ -z "$fp_eff" ]  && fp_eff=0
      fp_att_total=$((fp_att_total + fp_att))
      fp_succ_total=$((fp_succ_total + fp_succ))
      fp_eff_total=$((fp_eff_total + fp_eff))
    fi
  done

  local avg_cpu
  avg_cpu=$(awk -v a="${CPUS[0]}" -v b="${CPUS[1]}" -v c="${CPUS[2]}" -v d="${CPUS[3]}" -v e="${CPUS[4]}" \
               'BEGIN{printf "%.3f", (a+b+c+d+e)/5}')

  # Cluster fastpath rates. Expressed as a percentage of attempts so the
  # column is easy to skim; divide by zero is guarded.
  local fp_rate fp_eff_rate
  fp_rate=$(awk -v s="$fp_succ_total" -v a="$fp_att_total" \
              'BEGIN{ if(a>0) printf "%.2f", 100.0*s/a; else printf "0.00" }')
  fp_eff_rate=$(awk -v s="$fp_eff_total" -v a="$fp_att_total" \
                  'BEGIN{ if(a>0) printf "%.2f", 100.0*s/a; else printf "0.00" }')

  # zoo2 = index 1, zoo3 = index 2.
  LAST_N=$N
  LAST_TPUT=$total
  LAST_Z2_P50=${P50S[1]}; LAST_Z2_P90=${P90S[1]}; LAST_Z2_P99=${P99S[1]}
  LAST_Z3_P50=${P50S[2]}; LAST_Z3_P90=${P90S[2]}; LAST_Z3_P99=${P99S[2]}
  LAST_Z1_CPU=${CPUS[0]}; LAST_Z2_CPU=${CPUS[1]}; LAST_Z3_CPU=${CPUS[2]}
  LAST_Z4_CPU=${CPUS[3]}; LAST_Z5_CPU=${CPUS[4]}
  LAST_AVG_CPU=$avg_cpu
  LAST_FP_ATT=$fp_att_total
  LAST_FP_SUCC=$fp_succ_total
  LAST_FP_EFF=$fp_eff_total
  LAST_FP_RATE=$fp_rate
  LAST_FP_EFF_RATE=$fp_eff_rate
}

record_row() {
  local stopped="$1"
  echo "$LAST_N,$LAST_TPUT,$LAST_Z2_P50,$LAST_Z2_P90,$LAST_Z2_P99,$LAST_Z3_P50,$LAST_Z3_P90,$LAST_Z3_P99,$LAST_Z1_CPU,$LAST_Z2_CPU,$LAST_Z3_CPU,$LAST_Z4_CPU,$LAST_Z5_CPU,$LAST_AVG_CPU,${LAST_FP_ATT:-0},${LAST_FP_SUCC:-0},${LAST_FP_EFF:-0},${LAST_FP_RATE:-0.00},${LAST_FP_EFF_RATE:-0.00},$stopped" >> "$OUT_CSV"
  printf "    N=%s tput=%s zoo2_p50=%s p90=%s p99=%s zoo3_p50=%s avg_cpu=%s fp_rate=%s%% fp_eff_rate=%s%% stopped=%s\n" \
    "$LAST_N" "$LAST_TPUT" "$LAST_Z2_P50" "$LAST_Z2_P90" "$LAST_Z2_P99" \
    "$LAST_Z3_P50" "$LAST_AVG_CPU" "${LAST_FP_RATE:-0.00}" "${LAST_FP_EFF_RATE:-0.00}" "$stopped"
}

tripped_stop() {
  # 1 if zoo2 p90 > STOP_P90_MS, else 0.
  awk -v v="$LAST_Z2_P90" -v s="$STOP_P90_MS" 'BEGIN{print (v>s)?1:0}'
}

echo "=========================================="
echo "Adaptive sweep: $LABEL (cfg=$CFG mode=$MODE, pin=core ${SERVER_CORE_ID})"
echo "=========================================="

# 1) Baseline at N=1 (client co-located with leader at zoo2) — sanity only
echo "  [baseline] running N=1..."
run_point 1
BASELINE_P50=$LAST_Z2_P50
bad=$(awk -v b="$BASELINE_P50" 'BEGIN{print (b<=0)?1:0}')
if [ "$bad" -eq 1 ]; then
  # Some configs hit a flaky shutdown crash at N=1 that prevents zoo2 from
  # flushing its csv even when the run itself processed commands cleanly.
  # The baseline is a sanity check; the meaningful data starts at N=50, so
  # warn and continue rather than aborting the whole sweep.
  echo "  [baseline] WARN: zoo2 p50 at N=1 is ${BASELINE_P50} (non-positive); skipping baseline gate."
  BASELINE_P50="-1"
else
  echo "  [baseline] zoo2 p50 at N=1 = ${BASELINE_P50}ms  -> SLO is p90 <= ${STOP_P90_MS}ms"
fi
record_row "baseline"

# 2) Initial probes at N=50, N=100.
declare -a probed_Ns=(50 100)
last_ok=1
first_stop=0
for N in "${probed_Ns[@]}"; do
  run_point "$N"
  hit=$(tripped_stop)
  record_row "$([ "$hit" -eq 1 ] && echo "stop" || echo "ok")"
  if [ "$hit" -eq 1 ]; then
    first_stop="$N"
    break
  fi
  last_ok="$N"
done

# 3) If neither tripped, extend.
if [ "$first_stop" -eq 0 ]; then
  for N in "${UP_SEQ[@]}"; do
    run_point "$N"
    hit=$(tripped_stop)
    record_row "$([ "$hit" -eq 1 ] && echo "stop" || echo "ok")"
    if [ "$hit" -eq 1 ]; then
      first_stop="$N"
      break
    fi
    last_ok="$N"
  done
fi

# 4) Bisect between last_ok and first_stop if we found a stop.
if [ "$first_stop" -ne 0 ]; then
  lo="$last_ok"; hi="$first_stop"
  while [ $((hi - lo)) -gt "$BISECT_TOL" ]; do
    mid=$(( (lo + hi) / 2 ))
    run_point "$mid"
    hit=$(tripped_stop)
    record_row "$([ "$hit" -eq 1 ] && echo "bisect-stop" || echo "bisect-ok")"
    if [ "$hit" -eq 1 ]; then
      hi="$mid"
    else
      lo="$mid"
    fi
  done
  echo "  [bisect] converged: last unsaturated=$lo, first saturated=$hi"

  # 4b) Dense probe: fill in the N values in [lo-PAD, hi+PAD] that the bisect
  # skipped, so we can pin down the throughput peak past the coarse boundary.
  dense_lo=$((lo - DENSE_PAD))
  dense_hi=$((hi + DENSE_PAD))
  [ "$dense_lo" -lt 2 ] && dense_lo=2
  measured=$(awk -F, 'NR>1 {print $1}' "$OUT_CSV" | sort -un)
  for N in $(seq "$dense_lo" "$dense_hi"); do
    if printf '%s\n' "$measured" | grep -qx "$N"; then
      continue
    fi
    run_point "$N"
    hit=$(tripped_stop)
    record_row "$([ "$hit" -eq 1 ] && echo "dense-stop" || echo "dense-ok")"
  done
else
  echo "  [warning] did not hit saturation in sweep range; extend UP_SEQ"
fi

# 4c) Optional user-supplied extra probes. Set EXTRA_NS="76 77 80 90" to
# force additional data points past the bisect range — useful for
# verifying that throughput really peaks at the in-SLO knee and doesn't
# keep climbing into the over-SLO region.
if [ -n "${EXTRA_NS:-}" ]; then
  measured=$(awk -F, 'NR>1 {print $1}' "$OUT_CSV" | sort -un)
  for N in $EXTRA_NS; do
    if printf '%s\n' "$measured" | grep -qx "$N"; then continue; fi
    run_point "$N"
    hit=$(tripped_stop)
    record_row "$([ "$hit" -eq 1 ] && echo "extra-stop" || echo "extra-ok")"
  done
fi

# 5) Pretty table (sorted by N ascending for readability).
echo ""
echo "=========================================="
echo "Summary table for $LABEL (SLO: zoo2_p90 <= ${STOP_P90_MS}ms)"
echo "=========================================="
{ head -1 "$OUT_CSV"; tail -n +2 "$OUT_CSV" | sort -t, -k1,1n; } | \
awk -F, 'NR==1 {
  printf "%4s %8s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %s\n",
    "N","tput","z2_p50","z2_p90","z2_p99","z3_p50","z3_p90","z3_p99",
    "z1_cpu","z2_cpu","z3_cpu","z4_cpu","z5_cpu","avg_cpu","fp_rate","fp_eff","note"
  next
}
{
  printf "%4s %8s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %7s %s\n",
    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$18,$19,$20
}'

# 6) Peak = argmax(tput) over rows with zoo2_p90 <= STOP_P90_MS.
echo ""
awk -F, -v slo="$STOP_P90_MS" '
  NR>1 && $20!="baseline" && $4+0 <= slo && $2+0 > max {
    max=$2+0; n=$1; p50=$3; p90=$4; p99=$5; fpr=$18; fper=$19; note=$20
  }
  END {
    if (max>0) printf "PEAK under SLO (p90<=%sms): N=%s tput=%s  z2_p50=%sms p90=%sms p99=%sms  fp_rate=%s%% fp_eff_rate=%s%%  [%s]\n",
                       slo, n, max, p50, p90, p99, fpr, fper, note
    else      print  "PEAK under SLO: none found (no row with p90<=" slo "ms)"
  }' "$OUT_CSV"

echo ""
echo "CSV written to $OUT_CSV"
